export interface NameResult {
  name: string;
  meaning: string;
  origin: string;
  gender: string;
}

const data: Record<string, NameResult[]> = {
  "viking-name-generator": [
    { name: "Sigurd", meaning: "Victorious Guardian", origin: "Old Norse", gender: "male" },
    { name: "Freydis", meaning: "Noble Woman", origin: "Old Norse", gender: "female" },
    { name: "Bjorn", meaning: "The Bear", origin: "Scandinavian", gender: "male" },
    { name: "Aslaug", meaning: "God-Betrothed", origin: "Mythic", gender: "female" },
    { name: "Hakon", meaning: "High Son", origin: "Old Norse", gender: "male" },
    { name: "Ingrid", meaning: "Beautiful Goddess", origin: "Nordic", gender: "female" },
    { name: "Ragnar", meaning: "Warrior of the Gods", origin: "Old Norse", gender: "male" },
    { name: "Astrid", meaning: "Divine Strength", origin: "Old Norse", gender: "female" },
    { name: "Erik", meaning: "Ruler of All", origin: "Old Norse", gender: "male" },
    { name: "Sigrid", meaning: "Victory Secret", origin: "Old Norse", gender: "female" },
    { name: "Leif", meaning: "Heir, Descendant", origin: "Old Norse", gender: "male" },
    { name: "Thyra", meaning: "Thunder Battle", origin: "Nordic", gender: "female" },
    { name: "Gunnar", meaning: "Warrior", origin: "Old Norse", gender: "male" },
    { name: "Freya", meaning: "Lady, Noble Woman", origin: "Old Norse", gender: "female" },
    { name: "Olaf", meaning: "Ancestor's Heir", origin: "Old Norse", gender: "male" },
    { name: "Helga", meaning: "Holy, Sacred", origin: "Old Norse", gender: "female" },
    { name: "Ivar", meaning: "Yew Warrior", origin: "Old Norse", gender: "male" },
    { name: "Runa", meaning: "Secret Knowledge", origin: "Old Norse", gender: "female" },
    { name: "Sven", meaning: "Young Warrior", origin: "Old Norse", gender: "male" },
    { name: "Solveig", meaning: "Strong Victory", origin: "Nordic", gender: "female" },
    { name: "Rollo", meaning: "Famous Spear", origin: "Old Norse", gender: "male" },
    { name: "Eira", meaning: "Mercy", origin: "Old Norse", gender: "female" },
    { name: "Ketil", meaning: "Kettle, Cauldron", origin: "Old Norse", gender: "male" },
    { name: " Thy", meaning: "Battle", origin: "Old Norse", gender: "female" },
    { name: "Frode", meaning: "Wise", origin: "Old Norse", gender: "male" },
    { name: "Alva", meaning: "Elf, Supernatural Being", origin: "Old Norse", gender: "female" },
    { name: "Hjalmar", meaning: "Helmet of the Gods", origin: "Old Norse", gender: "male" },
    { name: "Brynhild", meaning: "Armored Battle", origin: "Old Norse", gender: "female" },
    { name: "Ulf", meaning: "Wolf", origin: "Old Norse", gender: "male" },
    { name: "Sigrunn", meaning: "Victory Secret", origin: "Old Norse", gender: "female" },
    { name: "Torsten", meaning: "Thor's Stone", origin: "Old Norse", gender: "male" },
    { name: "Gertrud", meaning: "Strength of the Spear", origin: "Germanic", gender: "female" },
    { name: "Arne", meaning: "Eagle", origin: "Old Norse", gender: "male" },
    { name: "Hilda", meaning: "Battle of the Rocks", origin: "Old Norse", gender: "female" },
    { name: "Fjolnir", meaning: "Giant", origin: "Mythic", gender: "male" },
    { name: "Ylva", meaning: "Wolf", origin: "Old Norse", gender: "female" },
    { name: "Baldur", meaning: "Prince of Light", origin: "Mythic", gender: "male" },
    { name: "Dagmar", meaning: "Day of Glory", origin: "Old Norse", gender: "female" },
    { name: "Skarde", meaning: "Scar", origin: "Old Norse", gender: "male" },
    { name: "Eldrid", meaning: "Ancient Fire", origin: "Nordic", gender: "female" },
    { name: "Guthrum", meaning: "Battle Sword", origin: "Old Norse", gender: "male" },
    { name: "Linnea", meaning: "Twin Flower", origin: "Nordic", gender: "female" },
    { name: "Aric", meaning: "Eagle Ruler", origin: "Old Norse", gender: "male" },
    { name: "Freja", meaning: "Noble Woman", origin: "Old Norse", gender: "female" },
    { name: "Kol", meaning: "Hollow Vessel", origin: "Old Norse", gender: "male" },
    { name: "Maren", meaning: "Of the Sea", origin: "Nordic", gender: "female" },
    { name: "Geir", meaning: "Spear", origin: "Old Norse", gender: "male" },
    { name: "Vigdis", meaning: "War Goddess", origin: "Old Norse", gender: "female" },
    { name: "Dren", meaning: "Sharp, Keen", origin: "Old Norse", gender: "male" },
    { name: "Liv", meaning: "Life, Protection", origin: "Old Norse", gender: "female" },
    { name: "Tormund", meaning: "Thor Protection", origin: "Old Norse", gender: "male" },
    { name: "Helga", meaning: "Holy", origin: "Old Norse", gender: "female" },
    { name: "Bjorn", meaning: "Bear", origin: "Scandinavian", gender: "male" },
    { name: "Asta", meaning: "God-like Love", origin: "Old Norse", gender: "female" },
    { name: "Egill", meaning: "Awe, Edge", origin: "Old Norse", gender: "male" },
    { name: "Ragna", meaning: "Counsel of the Gods", origin: "Old Norse", gender: "female" },
    { name: "Njal", meaning: "Champion", origin: "Old Norse", gender: "male" },
    { name: "Svana", meaning: "Swan", origin: "Old Norse", gender: "female" },
  ],

  "rap-name-generator": [
    { name: "Lil Shadow", meaning: "Quiet but deadly", origin: "Modern", gender: "male" },
    { name: "MC Frostbyte", meaning: "Cold precision on the mic", origin: "Modern", gender: "male" },
    { name: "Viper", meaning: "Venomous flow", origin: "Classic", gender: "male" },
    { name: "Kash Flow", meaning: "Cash money rhythm", origin: "Modern", gender: "male" },
    { name: "Ace Venom", meaning: "Deadly accuracy", origin: "Modern", gender: "male" },
    { name: "Z-Roc", meaning: "Rock solid", origin: "Classic", gender: "male" },
    { name: "Ghost 6ix", meaning: "Haunting presence", origin: "Modern", gender: "male" },
    { name: "Big Lazer", meaning: "Explosive energy", origin: "Modern", gender: "male" },
    { name: "Mack Slade", meaning: "Smooth operator", origin: "Classic", gender: "male" },
    { name: "Dolla $ign", meaning: "All about the money", origin: "Modern", gender: "male" },
    { name: "Trill E", meaning: "Real and authentic", origin: "Street", gender: "male" },
    { name: "J. Rocc", meaning: "Just rocking", origin: "Classic", gender: "male" },
    { name: "Slick Rick 2", meaning: "Smooth talking sequel", origin: "Classic", gender: "male" },
    { name: "Yung Apex", meaning: "Young peak", origin: "Modern", gender: "male" },
    { name: "C Notes", meaning: "See money", origin: "Classic", gender: "male" },
    { name: "Drift King V", meaning: "Smooth operator", origin: "Modern", gender: "male" },
    { name: "Raw V", meaning: "Raw and uncut", origin: "Modern", gender: "male" },
    { name: "Krown Prince", meaning: "Royal flow", origin: "Modern", gender: "male" },
    { name: "Hitta Slay", meaning: "Find the style", origin: "Modern", gender: "male" },
    { name: "Ceezy B", meaning: "Easy breezy", origin: "Modern", gender: "male" },
    { name: "Mack Montana", meaning: "Smooth operator", origin: "Modern", gender: "male" },
    { name: "O.G. Flow", meaning: "Original gangsta", origin: "Classic", gender: "male" },
    { name: "Young Phantom", meaning: "Sneak attack", origin: "Modern", gender: "male" },
    { name: "Skrillz Kay", meaning: "Spelling skills", origin: "Modern", gender: "male" },
    { name: "Hardo B", meaning: "Hardcore", origin: "Street", gender: "male" },
    { name: "Rich Dust", meaning: "Wealthy vibe", origin: "Modern", gender: "male" },
    { name: "Spit Fire", meaning: "Hot lyrics", origin: "Classic", gender: "male" },
    { name: "Kash Money", meaning: "Fortune seeker", origin: "Modern", gender: "male" },
    { name: "Rydah 7", meaning: "Rider", origin: "Modern", gender: "male" },
    { name: "P.Dot", meaning: "Primary dot", origin: "Modern", gender: "male" },
    { name: "Ice Lord", meaning: "Cold blooded", origin: "Classic", gender: "male" },
    { name: "Yung Str8", meaning: "Young straight", origin: "Modern", gender: "male" },
    { name: "Flex K", meaning: "Flexing king", origin: "Modern", gender: "male" },
    { name: "Riq 4", meaning: "Classic rhythm", origin: "Modern", gender: "male" },
    { name: "Wonda M", meaning: "Wonderful", origin: "Modern", gender: "male" },
    { name: "Blacc Omen", meaning: "Dark aura", origin: "Modern", gender: "male" },
    { name: "Thunda M", meaning: "Thunder", origin: "Modern", gender: "male" },
    { name: "Cash Caviar", meaning: "Luxury lifestyle", origin: "Modern", gender: "male" },
    { name: "Stack Bundles", meaning: "Money collector", origin: "Modern", gender: "male" },
    { name: "Nappy Roots", meaning: "Natural vibe", origin: "Modern", gender: "male" },
    { name: "Banger Bros", meaning: "Hit makers", origin: "Modern", gender: "male" },
    { name: "Gutta T", meaning: "Guts", origin: "Street", gender: "male" },
    { name: "Finesse Kid", meaning: "Smooth operator", origin: "Modern", gender: "male" },
    { name: "Savage J", meaning: "Savage", origin: "Modern", gender: "male" },
    { name: "B.M.I.", meaning: "Bigger money incoming", origin: "Modern", gender: "male" },
    { name: "Klassik E", meaning: "Timeless", origin: "Modern", gender: "male" },
    { name: "Trill G", meaning: "Gangsta trill", origin: "Street", gender: "male" },
    { name: "Cobra C", meaning: "Dangerous", origin: "Classic", gender: "male" },
    { name: "Vivid Visuals", meaning: "Picture perfect", origin: "Modern", gender: "male" },
    { name: "Roc Solid", meaning: "Reliable", origin: "Classic", gender: "male" },
    { name: "Lo Key", meaning: "Low key", origin: "Modern", gender: "male" },
    { name: "D-Brick", meaning: "Street foundation", origin: "Street", gender: "male" },
    { name: "Frost E", meaning: "Cold style", origin: "Modern", gender: "male" },
    { name: "Jay Swag", meaning: "Style icon", origin: "Modern", gender: "male" },
    { name: "Red Rum", meaning: "Murder", origin: "Classic", gender: "male" },
    { name: "Moe Lag", meaning: "Chilling", origin: "Modern", gender: "male" },
    { name: "G-Funk Era", meaning: "Smooth funk", origin: "Classic", gender: "male" },
    { name: "Traphouse Z", meaning: "Music dungeon", origin: "Modern", gender: "male" },
    { name: "Crown Royal", meaning: "Luxury", origin: "Classic", gender: "male" },
  ],

  "elf-name-generator": [
    { name: "Aelindra", meaning: "Star elf", origin: "High Fantasy", gender: "female" },
    { name: "Thalion", meaning: "Spring valley", origin: "High Fantasy", gender: "male" },
    { name: "Lirael", meaning: "Night music", origin: "High Fantasy", gender: "female" },
    { name: "Caelwyn", meaning: "Eternal beauty", origin: "High Fantasy", gender: "female" },
    { name: "Aerindor", meaning: "Star of the valley", origin: "High Fantasy", gender: "male" },
    { name: "Sylvara", meaning: "Silver forest", origin: "High Fantasy", gender: "female" },
    { name: "Eryndor", meaning: "Elf of the dawn", origin: "High Fantasy", gender: "male" },
    { name: "Nimue", meaning: "Lady of the lake", origin: "Mythic", gender: "female" },
    { name: "Galadhon", meaning: "Woodland dweller", origin: "High Fantasy", gender: "male" },
    { name: "Elowen", meaning: "From the elm tree", origin: "Celtic", gender: "female" },
    { name: "Aradhel", meaning: "Noble elf", origin: "High Fantasy", gender: "female" },
    { name: "Fenrith", meaning: "Shadow stalker", origin: "Dark Fantasy", gender: "male" },
    { name: "Vaelith", meaning: "Flower of light", origin: "High Fantasy", gender: "female" },
    { name: "Lorien", meaning: "Dream of paradise", origin: "High Fantasy", gender: "female" },
    { name: "Caelum", meaning: "Sky dweller", origin: "High Fantasy", gender: "male" },
    { name: "Aelwen", meaning: "Fair elf maiden", origin: "Celtic", gender: "female" },
    { name: "Tharion", meaning: "Eagle spirit", origin: "High Fantasy", gender: "male" },
    { name: "Seraphina", meaning: "Flaming winged", origin: "High Fantasy", gender: "female" },
    { name: "Aldaron", meaning: "Old tree", origin: "High Fantasy", gender: "male" },
    { name: "Lothloriel", meaning: "Flower of dream", origin: "High Fantasy", gender: "female" },
    { name: "Faelorn", meaning: "Shadow hunter", origin: "Dark Fantasy", gender: "male" },
    { name: "Aranel", meaning: "Divine spark", origin: "High Fantasy", gender: "female" },
    { name: "Celborn", meaning: "Born of the sky", origin: "High Fantasy", gender: "male" },
    { name: "Idril", meaning: "Sparkling water", origin: "High Fantasy", gender: "female" },
    { name: "Maedhros", meaning: "Famous elf lord", origin: "High Fantasy", gender: "male" },
    { name: "Aredhel", meaning: "Noble elf lady", origin: "High Fantasy", gender: "female" },
    { name: "Finrod", meaning: "Wise brow", origin: "High Fantasy", gender: "male" },
    { name: "Celebrian", meaning: "Daughter of silver", origin: "High Fantasy", gender: "female" },
    { name: "Elrond", meaning: "Star dome", origin: "High Fantasy", gender: "male" },
    { name: "Arwenkf", meaning: "Maid of the elves", origin: "High Fantasy", gender: "female" },
    { name: "Thranduil", meaning: "Forest dweller", origin: "High Fantasy", gender: "male" },
    { name: "Galadriel", meaning: "Radiant garland", origin: "High Fantasy", gender: "female" },
    { name: "Elladan", meaning: "Elf of the valley", origin: "High Fantasy", gender: "male" },
    { name: "Elanor", meaning: "Star sun", origin: "High Fantasy", gender: "female" },
    { name: "Haldir", meaning: "Hidden elf", origin: "High Fantasy", gender: "male" },
    { name: "Nimrodel", meaning: "Lady of the white water", origin: "High Fantasy", gender: "female" },
    { name: "Legolas", meaning: "Green leaf", origin: "High Fantasy", gender: "male" },
    { name: "Tinuviel", meaning: "Nightingale", origin: "High Fantasy", gender: "female" },
    { name: "Gildor", meaning: "Star light", origin: "High Fantasy", gender: "male" },
    { name: "Luthien", meaning: "Enchantment", origin: "High Fantasy", gender: "female" },
    { name: "Celeborn", meaning: "Silver tree", origin: "High Fantasy", gender: "male" },
    { name: "Amarien", meaning: "Bitter beautiful", origin: "High Fantasy", gender: "female" },
    { name: "Orophin", meaning: "Pine", origin: "High Fantasy", gender: "male" },
    { name: "Nimrodel", meaning: "White lady", origin: "High Fantasy", gender: "female" },
    { name: "Rohan", meaning: "Horse country", origin: "High Fantasy", gender: "male" },
    { name: "Finduilas", meaning: "Hair of the mallorn", origin: "High Fantasy", gender: "female" },
    { name: "Erestor", meaning: "Solitary", origin: "High Fantasy", gender: "male" },
    { name: "Melian", meaning: "Gift of the trees", origin: "High Fantasy", gender: "female" },
    { name: "Cirdan", meaning: "Ship builder", origin: "High Fantasy", gender: "male" },
    { name: "Miriel", meaning: "Jewelled", origin: "High Fantasy", gender: "female" },
    { name: "Glorfindel", meaning: "Golden star", origin: "High Fantasy", gender: "male" },
    { name: "Idril", meaning: "Silver sparkle", origin: "High Fantasy", gender: "female" },
    { name: "Enerdhil", meaning: "Sun of the forge", origin: "High Fantasy", gender: "male" },
    { name: "Earwen", meaning: "Sea maiden", origin: "High Fantasy", gender: "female" },
    { name: "Ingwion", meaning: "Son of Ing", origin: "High Fantasy", gender: "male" },
    { name: "Valanher", meaning: "Elf of grace", origin: "High Fantasy", gender: "female" },
    { name: "Falathar", meaning: "Dweller by the shore", origin: "High Fantasy", gender: "male" },
    { name: "Aelinor", meaning: "Light of the lake", origin: "High Fantasy", gender: "female" },
  ],

  "cat-name-generator": [
    { name: "Mochi", meaning: "Soft and sweet like the treat", origin: "Japanese", gender: "any" },
    { name: "Luna", meaning: "Moon goddess of the night", origin: "Latin", gender: "female" },
    { name: "Milo", meaning: "Merciful soldier", origin: "Greek", gender: "male" },
    { name: "Nova", meaning: "New star", origin: "Latin", gender: "female" },
    { name: "Oliver", meaning: "Olive tree of peace", origin: "Latin", gender: "male" },
    { name: "Bella", meaning: "Beautiful", origin: "Latin", gender: "female" },
    { name: "Leo", meaning: "Lion", origin: "Latin", gender: "male" },
    { name: "Cleo", meaning: "Glory of the father", origin: "Greek", gender: "female" },
    { name: "Felix", meaning: "Happy and fortunate", origin: "Latin", gender: "male" },
    { name: "Willow", meaning: "Graceful and flexible", origin: "English", gender: "female" },
    { name: "Oscar", meaning: "Deer friend of the gods", origin: "Irish", gender: "male" },
    { name: "Nala", meaning: "Queen, successful", origin: "Swahili", gender: "female" },
    { name: "Simba", meaning: "Lion", origin: "Swahili", gender: "male" },
    { name: "Minnie", meaning: "Beloved", origin: "Germanic", gender: "female" },
    { name: "Charlie", meaning: "Free man", origin: "Germanic", gender: "any" },
    { name: "Shadow", meaning: "Dark silhouette", origin: "English", gender: "any" },
    { name: "Cinnamon", meaning: "Warm spice", origin: "English", gender: "female" },
    { name: "Tigger", meaning: "Tiger-like energy", origin: "English", gender: "male" },
    { name: "Ginger", meaning: "Red-haired spice", origin: "English", gender: "female" },
    { name: "Smokey", meaning: "Like grey smoke", origin: "English", gender: "male" },
    { name: "Pepper", meaning: "Bold and spicy", origin: "English", gender: "any" },
    { name: "Gizmo", meaning: "Small mechanical device", origin: "English", gender: "male" },
    { name: "Tiger", meaning: "Striped predator", origin: "English", gender: "any" },
    { name: "Suki", meaning: "Beloved", origin: "Japanese", gender: "female" },
    { name: "Jasper", meaning: "Treasure", origin: "Persian", gender: "male" },
    { name: "Zoe", meaning: "Life", origin: "Greek", gender: "female" },
    { name: "Winston", meaning: "Wine town", origin: "English", gender: "male" },
    { name: "Lucy", meaning: "Light", origin: "Latin", gender: "female" },
    { name: "Midnight", meaning: "Darkest hour", origin: "English", gender: "any" },
    { name: "Maggie", meaning: "Pearl", origin: "Greek", gender: "female" },
    { name: "Oscar", meaning: "Champion of the gods", origin: "Irish", gender: "male" },
    { name: "Sophie", meaning: "Wisdom", origin: "Greek", gender: "female" },
    { name: "Theo", meaning: "Gift of God", origin: "Greek", gender: "male" },
    { name: "Coco", meaning: "Chocolate bean", origin: "Spanish", gender: "female" },
    { name: "Biscuit", meaning: "Golden brown treat", origin: "English", gender: "male" },
    { name: "Peanut", meaning: "Small but mighty", origin: "English", gender: "any" },
    { name: "Daisy", meaning: "Day's eye flower", origin: "English", gender: "female" },
    { name: "Rocky", meaning: "Stone-like strength", origin: "English", gender: "male" },
    { name: "Sasha", meaning: "Defender of mankind", origin: "Russian", gender: "any" },
    { name: "Bandit", meaning: "Outlaw with heart", origin: "English", gender: "male" },
    { name: "Millie", meaning: "Merciful", origin: "Germanic", gender: "female" },
    { name: "Oreo", meaning: "Black and white cookie", origin: "American", gender: "any" },
    { name: "Loki", meaning: "Trickster god", origin: "Norse", gender: "male" },
    { name: "Callie", meaning: "Most beautiful", origin: "Greek", gender: "female" },
    { name: "Muffin", meaning: "Sweet little treat", origin: "English", gender: "any" },
    { name: "Dusty", meaning: "Grey-brown powder", origin: "English", gender: "any" },
    { name: "Patches", meaning: "Colorful spots", origin: "English", gender: "female" },
    { name: "Romeo", meaning: "Romeo — lover boy", origin: "Italian", gender: "male" },
    { name: "Misty", meaning: "Grey morning fog", origin: "English", gender: "female" },
    { name: "Boots", meaning: "Foot coverings", origin: "English", gender: "any" },
    { name: "Socks", meaning: "Paw markings", origin: "English", gender: "any" },
    { name: "Bubbles", meaning: "Playful and light", origin: "English", gender: "female" },
    { name: "Maple", meaning: "Sweet tree", origin: "English", gender: "any" },
    { name: "Toby", meaning: "God is good", origin: "Hebrew", gender: "male" },
    { name: "Olive", meaning: "Peace tree fruit", origin: "Latin", gender: "female" },
    { name: "Salem", meaning: "Peaceful", origin: "Hebrew", gender: "any" },
    { name: "Pumpkin", meaning: "Orange autumn treat", origin: "English", gender: "any" },
  ],

  "horse-name-generator": [
    { name: "Thunderbolt", meaning: "Lightning strike power", origin: "English", gender: "male" },
    { name: "Midnight Star", meaning: "Shining in darkness", origin: "English", gender: "female" },
    { name: "Iron Will", meaning: "Unbreakable determination", origin: "English", gender: "male" },
    { name: "Golden Arrow", meaning: "Swift and valuable", origin: "English", gender: "female" },
    { name: "Shadowfax", meaning: "Shadow swift messenger", origin: "High Fantasy", gender: "male" },
    { name: "Spirit", meaning: "Free wild soul", origin: "English", gender: "any" },
    { name: "Rocinante", meaning: "Old worn-out horse", origin: "Spanish", gender: "male" },
    { name: "Beauty", meaning: "Graceful appearance", origin: "English", gender: "female" },
    { name: "Comanche", meaning: "Warrior", origin: "Native American", gender: "male" },
    { name: "Phar Lap", meaning: "Golden horse", origin: "Australian", gender: "male" },
    { name: "Seabiscuit", meaning: "Fierce underdog", origin: "American", gender: "male" },
    { name: "Kincsem", meaning: "My darling", origin: "Hungarian", gender: "female" },
    { name: "Man o War", meaning: "Warrior of men", origin: "English", gender: "male" },
    { name: "Red Rum", meaning: "Dark bay champion", origin: "English", gender: "male" },
    { name: "Bucephalus", meaning: "Ox-head, warlike", origin: "Greek", gender: "male" },
    { name: "Incitatus", meaning: "Swift as lightning", origin: "Latin", gender: "male" },
    { name: "Sleipnir", meaning: "The eight-legged god horse", origin: "Norse", gender: "male" },
    { name: "Epona", meaning: "Goddess of horses", origin: "Celtic", gender: "female" },
    { name: "Argent", meaning: "Silver, noble metal", origin: "French", gender: "male" },
    { name: "Starlight", meaning: "Dancing in the night", origin: "English", gender: "female" },
    { name: "Rustler", meaning: "Bold mover", origin: "American", gender: "male" },
    { name: "Palomino", meaning: "Golden coat color", origin: "Spanish", gender: "any" },
    { name: "Buckskin", meaning: "Tan with dark points", origin: "American", gender: "any" },
    { name: "Cerulean", meaning: "Deep sky blue", origin: "Latin", gender: "any" },
    { name: "Vanquish", meaning: "To conquer", origin: "Latin", gender: "male" },
    { name: "Ember", meaning: "Glowing coal", origin: "English", gender: "female" },
    { name: "Avalanche", meaning: "Crushing force", origin: "French", gender: "male" },
    { name: "Celestine", meaning: "Heavenly, divine", origin: "Latin", gender: "female" },
    { name: "Bastion", meaning: "Defensive stronghold", origin: "French", gender: "male" },
    { name: "Desert Rose", meaning: "Beauty in harsh land", origin: "English", gender: "female" },
    { name: "Tornado", meaning: "Spinning destruction", origin: "Spanish", gender: "male" },
    { name: "Sapphire", meaning: "Precious blue gem", origin: "Greek", gender: "female" },
    { name: "Mustang", meaning: "Wild horse", origin: "Spanish", gender: "any" },
    { name: "Lakota", meaning: "Friends, allies", origin: "Native American", gender: "any" },
    { name: "Zephyr", meaning: "Gentle west wind", origin: "Greek", gender: "any" },
    { name: "Aurora", meaning: "Dawn, sunrise goddess", origin: "Latin", gender: "female" },
    { name: "Cayenne", meaning: "Hot pepper spice", origin: "American", gender: "any" },
    { name: "Pepper", meaning: "Bold and spicy", origin: "English", gender: "any" },
    { name: "Storm", meaning: "Wild weather", origin: "English", gender: "any" },
    { name: "Cloud Nine", meaning: "Ultimate happiness", origin: "English", gender: "any" },
    { name: "Pecos Bill", meaning: "Legendary cowboy", origin: "American", gender: "male" },
    { name: "Dolly", meaning: "Gift of God", origin: "Greek", gender: "female" },
    { name: "Trigger", meaning: "Quick shooter", origin: "American", gender: "male" },
    { name: "Silver", meaning: "Precious metal", origin: "English", gender: "any" },
    { name: "Duke", meaning: "Noble leader", origin: "English", gender: "male" },
    { name: "Princess", meaning: "Royal female", origin: "English", gender: "female" },
    { name: "Champion", meaning: "Winner", origin: "English", gender: "any" },
    { name: "Firefly", meaning: "Glowing night insect", origin: "English", gender: "any" },
    { name: "Truffle", meaning: "Rare delicacy", origin: "French", gender: "female" },
    { name: "Maverick", meaning: "Independent spirit", origin: "American", gender: "any" },
    { name: "Rosie", meaning: "Rose", origin: "Latin", gender: "female" },
    { name: "Blaze", meaning: "Flame of fire", origin: "English", gender: "any" },
    { name: "Fancy", meaning: "Elaborate, stylish", origin: "English", gender: "female" },
    { name: "Ranger", meaning: "Guardian of the range", origin: "American", gender: "any" },
    { name: "Molly", meaning: "Star of the sea", origin: "Greek", gender: "female" },
    { name: "Cody", meaning: "Helpful pillow", origin: "American", gender: "any" },
  ],

  "dj-name-generator": [
    { name: "DJ Frostbyte", meaning: "Cold digital cuts", origin: "Modern", gender: "any" },
    { name: "MC Bassdrop", meaning: "Low-end frequency", origin: "Modern", gender: "any" },
    { name: "DJ Phantom", meaning: "Ghostly presence", origin: "Modern", gender: "any" },
    { name: "Voltage V", meaning: "Electric intensity", origin: "Modern", gender: "any" },
    { name: "DJ Cipher", meaning: "Code master", origin: "Modern", gender: "any" },
    { name: "Neon Groove", meaning: "Bright rhythm", origin: "Modern", gender: "any" },
    { name: "DJ Synthwave", meaning: "Retro future sound", origin: "Modern", gender: "any" },
    { name: "Pulse 808", meaning: "Heartbeat drum machine", origin: "Modern", gender: "any" },
    { name: "DJ Mosaic", meaning: "Blending pieces", origin: "Modern", gender: "any" },
    { name: "Bassiq", meaning: "Bass music", origin: "Modern", gender: "any" },
    { name: "DJ Eclipse", meaning: "Darkening moment", origin: "Modern", gender: "any" },
    { name: "Frequency X", meaning: "Unknown sound wave", origin: "Modern", gender: "any" },
    { name: "DJ Ripple", meaning: "Spreading waves", origin: "Modern", gender: "any" },
    { name: "Techno Templar", meaning: "Electronic warrior", origin: "Modern", gender: "any" },
    { name: "DJ Zenith", meaning: "Highest point", origin: "Modern", gender: "any" },
    { name: "Groove Merchant", meaning: "Rhythm trader", origin: "Modern", gender: "any" },
    { name: "DJ Vortex", meaning: "Spinning sound", origin: "Modern", gender: "any" },
    { name: "Melody Riot", meaning: "Harmonic uprising", origin: "Modern", gender: "any" },
    { name: "DJ Hologram", meaning: "3D illusion", origin: "Modern", gender: "any" },
    { name: "Subwrecker", meaning: "Deep bass destroyer", origin: "Modern", gender: "any" },
    { name: "DJ Apex", meaning: "Peak performance", origin: "Modern", gender: "any" },
    { name: "Cortex", meaning: "Brain center", origin: "Modern", gender: "any" },
    { name: "DJ Spectrum", meaning: "Full color sound", origin: "Modern", gender: "any" },
    { name: "Overload", meaning: "Excessive energy", origin: "Modern", gender: "any" },
    { name: "DJ Reverb", meaning: "Echoed sound", origin: "Modern", gender: "any" },
    { name: "Sonicbloom", meaning: "Sound flower", origin: "Modern", gender: "any" },
    { name: "DJ Quartz", meaning: "Crystal clear", origin: "Modern", gender: "any" },
    { name: "Phonograph", meaning: "Sound writer", origin: "Modern", gender: "any" },
    { name: "DJ Prism", meaning: "Light refractor", origin: "Modern", gender: "any" },
    { name: "Flux capacitor", meaning: "Time travel energy", origin: "Modern", gender: "any" },
    { name: "DJ Cascade", meaning: "Falling water sound", origin: "Modern", gender: "any" },
    { name: "Warp Drive", meaning: "Faster than light", origin: "Modern", gender: "any" },
    { name: "DJ Chronos", meaning: "Time god", origin: "Modern", gender: "any" },
    { name: "Noise floor", meaning: "Ambient static", origin: "Modern", gender: "any" },
    { name: "DJ Hyperdrive", meaning: "Extreme speed", origin: "Modern", gender: "any" },
    { name: "Signal Boost", meaning: "Amplified transmission", origin: "Modern", gender: "any" },
    { name: "DJ Matrix", meaning: "Digital grid", origin: "Modern", gender: "any" },
    { name: "Decoherence", meaning: "Quantum breakup", origin: "Modern", gender: "any" },
    { name: "DJ Nova", meaning: "New star", origin: "Modern", gender: "any" },
    { name: "Stereophile X", meaning: "Sound lover", origin: "Modern", gender: "any" },
    { name: "DJ Kinetic", meaning: "Motion energy", origin: "Modern", gender: "any" },
    { name: "Wavelength", meaning: "Sound distance", origin: "Modern", gender: "any" },
    { name: "DJ Photon", meaning: "Light particle", origin: "Modern", gender: "any" },
    { name: "Phase shift", meaning: "Timing change", origin: "Modern", gender: "any" },
    { name: "DJ Atmo", meaning: "Atmospheric", origin: "Modern", gender: "any" },
    { name: "Resonance", meaning: "Sympathetic vibration", origin: "Modern", gender: "any" },
    { name: "DJ Quasar", meaning: "Distant star energy", origin: "Modern", gender: "any" },
    { name: "Harmonic", meaning: "Musical harmony", origin: "Modern", gender: "any" },
    { name: "DJ Magnetism", meaning: "Attraction force", origin: "Modern", gender: "any" },
    { name: "Stereophonic", meaning: "Two-channel sound", origin: "Modern", gender: "any" },
    { name: "DJ Cosmos", meaning: "Universal space", origin: "Modern", gender: "any" },
    { name: "Amplitude", meaning: "Wave height", origin: "Modern", gender: "any" },
    { name: "DJ Lumen", meaning: "Light unit", origin: "Modern", gender: "any" },
    { name: "Saturate", meaning: "Full blend", origin: "Modern", gender: "any" },
    { name: "DJ Quark", meaning: "Matter particle", origin: "Modern", gender: "any" },
    { name: "Timestretch", meaning: "Duration change", origin: "Modern", gender: "any" },
  ],

  "middle-name-generator": [
    { name: "James", meaning: "Supplanter", origin: "Hebrew", gender: "male" },
    { name: "Rose", meaning: "Beautiful flower", origin: "Latin", gender: "female" },
    { name: "Alexander", meaning: "Defender of men", origin: "Greek", gender: "male" },
    { name: "Grace", meaning: "Divine favor", origin: "Latin", gender: "female" },
    { name: "Michael", meaning: "Who is like God", origin: "Hebrew", gender: "male" },
    { name: "Elizabeth", meaning: "My God is abundance", origin: "Hebrew", gender: "female" },
    { name: "William", meaning: "Resolute protector", origin: "Germanic", gender: "male" },
    { name: "Anne", meaning: "Gracious", origin: "Hebrew", gender: "female" },
    { name: "Edward", meaning: "Wealthy guardian", origin: "English", gender: "male" },
    { name: "Claire", meaning: "Clear, bright", origin: "French", gender: "female" },
    { name: "Henry", meaning: "Ruler of the home", origin: "Germanic", gender: "male" },
    { name: "Maureen", meaning: "Sea star", origin: "Irish", gender: "female" },
    { name: "Charles", meaning: "Free man", origin: "Germanic", gender: "male" },
    { name: "Joy", meaning: "Great happiness", origin: "English", gender: "female" },
    { name: "Robert", meaning: "Bright fame", origin: "Germanic", gender: "male" },
    { name: "Faith", meaning: "Belief and trust", origin: "English", gender: "female" },
    { name: "Thomas", meaning: "Twin", origin: "Aramaic", gender: "male" },
    { name: "Hope", meaning: "Optimistic expectation", origin: "English", gender: "female" },
    { name: "George", meaning: "Farmer", origin: "Greek", gender: "male" },
    { name: "Blair", meaning: "Plain, battlefield", origin: "Scottish", gender: "any" },
    { name: "Patrick", meaning: "Nobleman", origin: "Latin", gender: "male" },
    { name: "Skye", meaning: "From the sky", origin: "Scottish", gender: "any" },
    { name: "David", meaning: "Beloved", origin: "Hebrew", gender: "male" },
    { name: "Quinn", meaning: "Wise", origin: "Irish", gender: "any" },
    { name: "Joseph", meaning: "He will add", origin: "Hebrew", gender: "male" },
    { name: "Taylor", meaning: "Tailor", origin: "English", gender: "any" },
    { name: "Matthew", meaning: "Gift of God", origin: "Hebrew", gender: "male" },
    { name: "Morgan", meaning: "Sea-born", origin: "Welsh", gender: "any" },
    { name: "Daniel", meaning: "God is my judge", origin: "Hebrew", gender: "male" },
    { name: "Reese", meaning: "Enthusiasm", origin: "Welsh", gender: "any" },
    { name: "Samuel", meaning: "Heard by God", origin: "Hebrew", gender: "male" },
    { name: "Avery", meaning: "Ruler of elves", origin: "English", gender: "any" },
    { name: "Christopher", meaning: "Bearer of Christ", origin: "Greek", gender: "male" },
    { name: "Harper", meaning: "Harp player", origin: "English", gender: "any" },
    { name: "Andrew", meaning: "Manly, courageous", origin: "Greek", gender: "male" },
    { name: "Riley", meaning: "Courageous", origin: "Irish", gender: "any" },
    { name: "Joshua", meaning: "God is salvation", origin: "Hebrew", gender: "male" },
    { name: "Finley", meaning: "Fair warrior", origin: "Irish", gender: "any" },
    { name: "Ryan", meaning: "Little king", origin: "Irish", gender: "any" },
    { name: "Jordan", meaning: "Flowing down", origin: "Hebrew", gender: "any" },
    { name: "Cole", meaning: "Swarthy", origin: "English", gender: "any" },
    { name: "Ethan", meaning: "Strong, firm", origin: "Hebrew", gender: "male" },
    { name: "Blake", meaning: "Dark, fair", origin: "English", gender: "any" },
    { name: "James", meaning: "Supplanter", origin: "Hebrew", gender: "male" },
    { name: "Sage", meaning: "Wise one", origin: "Latin", gender: "any" },
    { name: "Anthony", meaning: "Priceless one", origin: "Latin", gender: "male" },
    { name: "Lane", meaning: "Narrow path", origin: "English", gender: "any" },
    { name: "Luke", meaning: "Light-giving", origin: "Greek", gender: "male" },
    { name: "Scout", meaning: "Explorer", origin: "English", gender: "any" },
    { name: "Mark", meaning: "Warlike", origin: "Latin", gender: "male" },
    { name: "Casey", meaning: "Brave in battle", origin: "Irish", gender: "any" },
    { name: "Paul", meaning: "Small, humble", origin: "Latin", gender: "male" },
    { name: "Eden", meaning: "Paradise", origin: "Hebrew", gender: "any" },
    { name: "Simon", meaning: "He has heard", origin: "Hebrew", gender: "male" },
    { name: "Wren", meaning: "Small bird", origin: "English", gender: "any" },
    { name: "Neil", meaning: "Champion", origin: "Irish", gender: "male" },
    { name: "Jules", meaning: "Youthful", origin: "Latin", gender: "any" },
    { name: "Dean", meaning: "Valley", origin: "English", gender: "any" },
    { name: "Rio", meaning: "River", origin: "Spanish", gender: "any" },
  ],
};

// Fallback names for slugs not explicitly defined
const fallbackNames: NameResult[] = [
  { name: "Aether", meaning: "Upper sky", origin: "Greek", gender: "any" },
  { name: "Nova", meaning: "New star", origin: "Latin", gender: "any" },
  { name: "Phoenix", meaning: "Reborn from ashes", origin: "Greek", gender: "any" },
  { name: "Atlas", meaning: "Bearer of the heavens", origin: "Greek", gender: "any" },
  { name: "Sage", meaning: "Wise one", origin: "Latin", gender: "any" },
  { name: "Echo", meaning: "Reflected sound", origin: "Greek", gender: "any" },
  { name: "Raven", meaning: "Dark bird", origin: "English", gender: "any" },
  { name: "Orion", meaning: "Hunter in the stars", origin: "Greek", gender: "any" },
  { name: "Ivy", meaning: "Faithfulness", origin: "English", gender: "any" },
  { name: "Dune", meaning: "Rolling sand hill", origin: "English", gender: "any" },
  { name: "Onyx", meaning: "Black gemstone", origin: "Greek", gender: "any" },
  { name: "Jade", meaning: "Green precious stone", origin: "Spanish", gender: "any" },
  { name: "Kai", meaning: "Sea", origin: "Hawaiian", gender: "any" },
  { name: "Zara", meaning: "Princess", origin: "Arabic", gender: "female" },
  { name: "Zane", meaning: "God is gracious", origin: "Hebrew", gender: "male" },
  { name: "Luna", meaning: "Moon", origin: "Latin", gender: "female" },
  { name: "Dante", meaning: "Enduring", origin: "Latin", gender: "male" },
  { name: "Lyra", meaning: "Lyre", origin: "Greek", gender: "female" },
  { name: "Cyrus", meaning: "Sun", origin: "Persian", gender: "male" },
  { name: "Iris", meaning: "Rainbow", origin: "Greek", gender: "female" },
  { name: "Asher", meaning: "Happy, blessed", origin: "Hebrew", gender: "male" },
  { name: "Sable", meaning: "Black fur", origin: "French", gender: "any" },
  { name: "Quinn", meaning: "Wise", origin: "Irish", gender: "any" },
  { name: "Cassia", meaning: "Cinnamon bark", origin: "Greek", gender: "female" },
  { name: "Rowan", meaning: "Little red one", origin: "Irish", gender: "any" },
  { name: "Sol", meaning: "Sun", origin: "Spanish", gender: "any" },
  { name: "Vesper", meaning: "Evening star", origin: "Latin", gender: "any" },
  { name: "Wren", meaning: "Small bird", origin: "English", gender: "any" },
  { name: "Bodhi", meaning: "Awakening", origin: "Sanskrit", gender: "any" },
  { name: "Anya", meaning: "Grace", origin: "Russian", gender: "female" },
  { name: "Felix", meaning: "Happy", origin: "Latin", gender: "any" },
  { name: "Sienna", meaning: "Red-orange earth", origin: "Italian", gender: "female" },
  { name: "Remy", meaning: "Oarsman", origin: "French", gender: "any" },
  { name: "Elara", meaning: "Moon of Jupiter", origin: "Greek", gender: "female" },
  { name: "Ren", meaning: "Lotus", origin: "Japanese", gender: "any" },
  { name: "Lyric", meaning: "Words of a song", origin: "Greek", gender: "any" },
  { name: "Ines", meaning: "Pure", origin: "Greek", gender: "female" },
  { name: "Cael", meaning: "Slender", origin: "Irish", gender: "male" },
  { name: "Vada", meaning: "Life", origin: "Germanic", gender: "female" },
  { name: "Xenon", meaning: "Strange gas", origin: "Greek", gender: "any" },
  { name: "Mira", meaning: "Wonderful", origin: "Latin", gender: "female" },
  { name: "Callan", meaning: "Battle rock", origin: "Scottish", gender: "male" },
  { name: "Nyx", meaning: "Night goddess", origin: "Greek", gender: "female" },
  { name: "Lark", meaning: "Singing bird", origin: "English", gender: "any" },
  { name: "Ares", meaning: "God of war", origin: "Greek", gender: "male" },
  { name: "Celeste", meaning: "Heavenly", origin: "Latin", gender: "female" },
  { name: "Jasper", meaning: "Treasurer", origin: "Persian", gender: "any" },
  { name: "Thalia", meaning: "Blooming", origin: "Greek", gender: "female" },
  { name: "Zephyr", meaning: "West wind", origin: "Greek", gender: "any" },
  { name: "Faye", meaning: "Fairy", origin: "English", gender: "female" },
  { name: "Idris", meaning: "Keen interpreter", origin: "Welsh", gender: "male" },
  { name: "Nova", meaning: "New", origin: "Latin", gender: "any" },
  { name: "Elio", meaning: "Sun", origin: "Greek", gender: "any" },
  { name: "Maren", meaning: "Of the sea", origin: "Latin", gender: "female" },
  { name: "Dax", meaning: "Leader", origin: "French", gender: "any" },
  { name: "Lena", meaning: "Light", origin: "Greek", gender: "female" },
];

function shuffle<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

export function generateNames(
  slug: string,
  gender: "male" | "female" | "all" = "all",
  count: number = 10
): NameResult[] {
  const pool = data[slug] ?? fallbackNames;

  const filtered =
    gender === "all"
      ? pool
      : pool.filter((n) => n.gender === gender || n.gender === "any");

  const source = filtered.length >= count ? filtered : [...filtered, ...fallbackNames];
  return shuffle(source).slice(0, count);
}
