/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#291800",
        "on-primary": "#ffffff",
        secondary: "#785a00",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#2d486d",
        "on-primary-fixed": "#001c3b",
        "primary-container": "#1e3a5f",
        "surface-container-high": "#e8e5ff",
        "primary-fixed": "#d5e3ff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#60410c",
        background: "#fcf8ff",
        "surface-tint": "#455f87",
        "surface-variant": "#e2e0fc",
        "on-tertiary-container": "#c69b5f",
        outline: "#74777f",
        "secondary-fixed": "#ffdf9b",
        "secondary-fixed-dim": "#edc157",
        "on-surface": "#1a1a2e",
        "on-primary-container": "#8aa4cf",
        "tertiary-fixed": "#ffddb2",
        "primary-fixed-dim": "#adc8f5",
        "surface-dim": "#dad7f3",
        "on-error-container": "#93000a",
        "surface-container": "#efecff",
        "tertiary-fixed-dim": "#edbf7f",
        "surface-bright": "#fcf8ff",
        "surface-container-highest": "#e2e0fc",
        "inverse-on-surface": "#f2efff",
        "outline-variant": "#c4c6cf",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#43474e",
        "inverse-primary": "#adc8f5",
        "tertiary-container": "#503300",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#765900",
        "on-secondary-fixed-variant": "#5b4300",
        "secondary-container": "#ffd167",
        surface: "#fcf8ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#1a1a2e",
        "on-secondary-fixed": "#251a00",
        "surface-container-low": "#f5f2ff",
        "inverse-surface": "#2f2e43",
        tertiary: "#341f00",
        primary: "#022448",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Plus Jakarta Sans"],
        label: ["Plus Jakarta Sans"],
      },
    },
  },
  plugins: [],
};
