import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Privacy Policy — CoolNameGen",
  description:
    "CoolNameGen does not collect personal data. This privacy policy explains our no-tracking, no-cookie approach.",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <Header />
      <main className="max-w-4xl mx-auto px-8 py-20">
        <h1 className="text-4xl font-headline font-black text-primary mb-8">
          Privacy Policy
        </h1>
        <div className="space-y-6 text-on-surface-variant font-body leading-relaxed">
          <p className="text-sm text-primary/60 uppercase tracking-widest font-label">
            Last updated: April 2026
          </p>

          <h2 className="text-2xl font-headline font-bold text-primary mt-8">
            1. No Data Collection
          </h2>
          <p>
            CoolNameGen is a static name generator. We do not collect, store, or
            process any personal data from visitors. There are no accounts, no
            login forms, and no data submissions of any kind.
          </p>

          <h2 className="text-2xl font-headline font-bold text-primary mt-8">
            2. Cookies
          </h2>
          <p>
            We do not use cookies, tracking pixels, or any form of browser
            storage to identify or profile users. The service is entirely
            cookie-free.
          </p>

          <h2 className="text-2xl font-headline font-bold text-primary mt-8">
            3. Third-Party Services
          </h2>
          <p>
            We use Google Fonts and Material Symbols for typography and iconography.
            These services may collect standard anonymous usage data in accordance
            with their own privacy policies. We do not share any data with
            third-party advertisers or analytics providers.
          </p>

          <h2 className="text-2xl font-headline font-bold text-primary mt-8">
            4. AI-Generated Content
          </h2>
          <p>
            Names generated by CoolNameGen are produced from curated linguistic
            databases. We do not use your inputs to train any machine learning
            model. You retain full rights to use any name you generate for your
            own creative, personal, or commercial purposes.
          </p>

          <h2 className="text-2xl font-headline font-bold text-primary mt-8">
            5. Children's Privacy
          </h2>
          <p>
            This service is not intended for children under 13 years of age. We
            do not knowingly collect any information from children.
          </p>

          <h2 className="text-2xl font-headline font-bold text-primary mt-8">
            6. Changes to This Policy
          </h2>
          <p>
            We may update this policy from time to time. Any changes will be
            posted on this page with an updated revision date.
          </p>

          <h2 className="text-2xl font-headline font-bold text-primary mt-8">
            7. Contact
          </h2>
          <p>
            If you have any questions about this privacy policy, please contact
            us at{" "}
            <a
              href="mailto:privacy@coolnamegen.com"
              className="text-primary underline"
            >
              privacy@coolnamegen.com
            </a>
            .
          </p>
        </div>

        <div className="mt-16 pt-8 border-t border-outline-variant">
          <Link href="/" className="text-primary font-bold hover:underline">
            ← Back to Home
          </Link>
        </div>
      </main>
      <Footer />
    </>
  );
}
